name: fupy
channels:
- conda-forge
- defaults
dependencies:
- python=3.7
- jupyterlab
- numpy
- pandas
- geopandas
- scipy
- matplotlib
- seaborn
- nbsphinx
- pip
- scikit-learn
- statsmodels
- descartes
- cartopy
- folium
- spyder
- wordcloud
- requests
- beautifulsoup4

- pip:
  - jupyter_sphinx_theme
  - stop-words
